/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TenantId = IDL.Nat;
export const ComplaintCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'other' : IDL.Null,
  'electricity' : IDL.Null,
  'water' : IDL.Null,
});
export const AddComplaintArgs = IDL.Record({
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'category' : ComplaintCategory,
});
export const ComplaintId = IDL.Nat;
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Complaint = IDL.Record({
  'id' : ComplaintId,
  'status' : ComplaintStatus,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'category' : ComplaintCategory,
});
export const SplitType = IDL.Variant({
  'equal' : IDL.Null,
  'weighted' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'electricity' : IDL.Null,
  'generator' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const AddExpenseArgs = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'splitType' : SplitType,
  'notes' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
});
export const ExpenseId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'splitType' : SplitType,
  'notes' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
});
export const AddGuestLogArgs = IDL.Record({
  'checkIn' : Timestamp,
  'guestName' : IDL.Text,
  'tenantId' : TenantId,
  'checkOut' : Timestamp,
  'extraCharge' : IDL.Nat,
});
export const GuestLogId = IDL.Nat;
export const GuestLog = IDL.Record({
  'id' : GuestLogId,
  'checkIn' : Timestamp,
  'guestName' : IDL.Text,
  'tenantId' : TenantId,
  'checkOut' : Timestamp,
  'extraCharge' : IDL.Nat,
});
export const AddMicroChargeArgs = IDL.Record({
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'amount' : IDL.Nat,
});
export const MicroChargeId = IDL.Nat;
export const MicroCharge = IDL.Record({
  'id' : MicroChargeId,
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'addedAt' : Timestamp,
  'amount' : IDL.Nat,
  'addedToRent' : IDL.Bool,
});
export const AddParcelArgs = IDL.Record({
  'description' : IDL.Text,
  'tenantId' : TenantId,
});
export const ParcelId = IDL.Nat;
export const Parcel = IDL.Record({
  'id' : ParcelId,
  'description' : IDL.Text,
  'isCollected' : IDL.Bool,
  'tenantId' : TenantId,
  'receivedAt' : Timestamp,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
});
export const AddPaymentArgs = IDL.Record({
  'status' : PaymentStatus,
  'method' : IDL.Opt(PaymentMethod),
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'tenantId' : TenantId,
  'paidDate' : IDL.Opt(Timestamp),
  'amount' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'method' : IDL.Opt(PaymentMethod),
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'tenantId' : TenantId,
  'paidDate' : IDL.Opt(Timestamp),
  'amount' : IDL.Nat,
});
export const AddRoomArgs = IDL.Record({
  'floor' : IDL.Nat,
  'isAC' : IDL.Bool,
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const RoomId = IDL.Nat;
export const Room = IDL.Record({
  'id' : RoomId,
  'floor' : IDL.Nat,
  'isAC' : IDL.Bool,
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const AddStaffTaskArgs = IDL.Record({
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'dueDate' : Timestamp,
});
export const StaffTaskId = IDL.Nat;
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
});
export const StaffTask = IDL.Record({
  'id' : StaffTaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'dueDate' : Timestamp,
});
export const BedId = IDL.Nat;
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AddTenantArgs = IDL.Record({
  'name' : IDL.Text,
  'checkInDate' : Timestamp,
  'idProof' : IDL.Text,
  'advancePaid' : IDL.Nat,
  'bedId' : BedId,
  'phone' : IDL.Text,
  'monthlyRent' : IDL.Nat,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
});
export const Tenant = IDL.Record({
  'id' : TenantId,
  'exitReason' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'checkInDate' : Timestamp,
  'idProof' : IDL.Text,
  'isActive' : IDL.Bool,
  'advancePaid' : IDL.Nat,
  'bedId' : BedId,
  'phone' : IDL.Text,
  'monthlyRent' : IDL.Nat,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
});
export const Bed = IDL.Record({
  'id' : BedId,
  'bedLabel' : IDL.Text,
  'tenantId' : IDL.Opt(TenantId),
  'isOccupied' : IDL.Bool,
  'roomId' : RoomId,
});
export const DashboardStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalExpensesThisMonth' : IDL.Nat,
  'occupiedBeds' : IDL.Nat,
  'totalBeds' : IDL.Nat,
  'totalTenants' : IDL.Nat,
  'activeTenants' : IDL.Nat,
  'highRiskTenants' : IDL.Nat,
  'overduePayments' : IDL.Nat,
  'openComplaints' : IDL.Nat,
  'paidPayments' : IDL.Nat,
  'totalRooms' : IDL.Nat,
});
export const MealRecordId = IDL.Nat;
export const MealRecord = IDL.Record({
  'id' : MealRecordId,
  'date' : Timestamp,
  'chargePerDay' : IDL.Nat,
  'tenantId' : TenantId,
  'isEating' : IDL.Bool,
});
export const ToggleMealArgs = IDL.Record({
  'date' : Timestamp,
  'chargePerDay' : IDL.Nat,
  'tenantId' : TenantId,
  'isEating' : IDL.Bool,
});
export const UpdateRoomArgs = IDL.Record({
  'id' : RoomId,
  'floor' : IDL.Nat,
  'isAC' : IDL.Bool,
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const UpdateTenantArgs = IDL.Record({
  'id' : TenantId,
  'exitReason' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'checkInDate' : Timestamp,
  'idProof' : IDL.Text,
  'isActive' : IDL.Bool,
  'advancePaid' : IDL.Nat,
  'bedId' : BedId,
  'phone' : IDL.Text,
  'monthlyRent' : IDL.Nat,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
});

export const idlService = IDL.Service({
  'addComplaint' : IDL.Func([AddComplaintArgs], [Complaint], []),
  'addExpense' : IDL.Func([AddExpenseArgs], [Expense], []),
  'addGuestLog' : IDL.Func([AddGuestLogArgs], [GuestLog], []),
  'addMicroCharge' : IDL.Func([AddMicroChargeArgs], [MicroCharge], []),
  'addParcel' : IDL.Func([AddParcelArgs], [Parcel], []),
  'addPayment' : IDL.Func([AddPaymentArgs], [Payment], []),
  'addRoom' : IDL.Func([AddRoomArgs], [Room], []),
  'addStaffTask' : IDL.Func([AddStaffTaskArgs], [StaffTask], []),
  'addTenant' : IDL.Func([AddTenantArgs], [Tenant], []),
  'assignBed' : IDL.Func([BedId, IDL.Opt(TenantId)], [IDL.Bool], []),
  'calculateMonthlyMessCharge' : IDL.Func(
      [TenantId, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'collectParcel' : IDL.Func([ParcelId], [IDL.Bool], []),
  'computeRiskLevel' : IDL.Func([TenantId, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteTenant' : IDL.Func([TenantId, IDL.Opt(IDL.Text)], [IDL.Bool], []),
  'freeBed' : IDL.Func([BedId], [IDL.Bool], []),
  'generateMonthlyPayments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Payment)],
      [],
    ),
  'getBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
  'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getComplaintsByTenant' : IDL.Func(
      [TenantId],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getGuestLogs' : IDL.Func([], [IDL.Vec(GuestLog)], ['query']),
  'getGuestLogsByTenant' : IDL.Func([TenantId], [IDL.Vec(GuestLog)], ['query']),
  'getInactiveTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'getMealRecords' : IDL.Func([], [IDL.Vec(MealRecord)], ['query']),
  'getMealRecordsByTenant' : IDL.Func(
      [TenantId],
      [IDL.Vec(MealRecord)],
      ['query'],
    ),
  'getMicroCharges' : IDL.Func([], [IDL.Vec(MicroCharge)], ['query']),
  'getOpenComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByTenant' : IDL.Func([TenantId], [IDL.Vec(Payment)], ['query']),
  'getPendingMicroCharges' : IDL.Func([], [IDL.Vec(MicroCharge)], ['query']),
  'getPendingTasks' : IDL.Func([], [IDL.Vec(StaffTask)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getStaffTasks' : IDL.Func([], [IDL.Vec(StaffTask)], ['query']),
  'getTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'getUncollectedParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getWhatsAppConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markChargeAddedToRent' : IDL.Func([MicroChargeId], [IDL.Bool], []),
  'sendWhatsAppReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'setWhatsAppConfig' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'toggleMeal' : IDL.Func([ToggleMealArgs], [MealRecord], []),
  'updateComplaintStatus' : IDL.Func(
      [ComplaintId, ComplaintStatus],
      [IDL.Bool],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [PaymentId, PaymentStatus, IDL.Opt(PaymentMethod), IDL.Opt(Timestamp)],
      [IDL.Bool],
      [],
    ),
  'updateRiskLevel' : IDL.Func([TenantId, RiskLevel], [IDL.Bool], []),
  'updateRoom' : IDL.Func([UpdateRoomArgs], [IDL.Bool], []),
  'updateTaskStatus' : IDL.Func([StaffTaskId, TaskStatus], [IDL.Bool], []),
  'updateTenant' : IDL.Func([UpdateTenantArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TenantId = IDL.Nat;
  const ComplaintCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'other' : IDL.Null,
    'electricity' : IDL.Null,
    'water' : IDL.Null,
  });
  const AddComplaintArgs = IDL.Record({
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'category' : ComplaintCategory,
  });
  const ComplaintId = IDL.Nat;
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Complaint = IDL.Record({
    'id' : ComplaintId,
    'status' : ComplaintStatus,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'category' : ComplaintCategory,
  });
  const SplitType = IDL.Variant({ 'equal' : IDL.Null, 'weighted' : IDL.Null });
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'electricity' : IDL.Null,
    'generator' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const AddExpenseArgs = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'splitType' : SplitType,
    'notes' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
  });
  const ExpenseId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'splitType' : SplitType,
    'notes' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
  });
  const AddGuestLogArgs = IDL.Record({
    'checkIn' : Timestamp,
    'guestName' : IDL.Text,
    'tenantId' : TenantId,
    'checkOut' : Timestamp,
    'extraCharge' : IDL.Nat,
  });
  const GuestLogId = IDL.Nat;
  const GuestLog = IDL.Record({
    'id' : GuestLogId,
    'checkIn' : Timestamp,
    'guestName' : IDL.Text,
    'tenantId' : TenantId,
    'checkOut' : Timestamp,
    'extraCharge' : IDL.Nat,
  });
  const AddMicroChargeArgs = IDL.Record({
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'amount' : IDL.Nat,
  });
  const MicroChargeId = IDL.Nat;
  const MicroCharge = IDL.Record({
    'id' : MicroChargeId,
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'addedAt' : Timestamp,
    'amount' : IDL.Nat,
    'addedToRent' : IDL.Bool,
  });
  const AddParcelArgs = IDL.Record({
    'description' : IDL.Text,
    'tenantId' : TenantId,
  });
  const ParcelId = IDL.Nat;
  const Parcel = IDL.Record({
    'id' : ParcelId,
    'description' : IDL.Text,
    'isCollected' : IDL.Bool,
    'tenantId' : TenantId,
    'receivedAt' : Timestamp,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
  const AddPaymentArgs = IDL.Record({
    'status' : PaymentStatus,
    'method' : IDL.Opt(PaymentMethod),
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'tenantId' : TenantId,
    'paidDate' : IDL.Opt(Timestamp),
    'amount' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'method' : IDL.Opt(PaymentMethod),
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'tenantId' : TenantId,
    'paidDate' : IDL.Opt(Timestamp),
    'amount' : IDL.Nat,
  });
  const AddRoomArgs = IDL.Record({
    'floor' : IDL.Nat,
    'isAC' : IDL.Bool,
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const RoomId = IDL.Nat;
  const Room = IDL.Record({
    'id' : RoomId,
    'floor' : IDL.Nat,
    'isAC' : IDL.Bool,
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const AddStaffTaskArgs = IDL.Record({
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'dueDate' : Timestamp,
  });
  const StaffTaskId = IDL.Nat;
  const TaskStatus = IDL.Variant({ 'pending' : IDL.Null, 'done' : IDL.Null });
  const StaffTask = IDL.Record({
    'id' : StaffTaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'dueDate' : Timestamp,
  });
  const BedId = IDL.Nat;
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AddTenantArgs = IDL.Record({
    'name' : IDL.Text,
    'checkInDate' : Timestamp,
    'idProof' : IDL.Text,
    'advancePaid' : IDL.Nat,
    'bedId' : BedId,
    'phone' : IDL.Text,
    'monthlyRent' : IDL.Nat,
    'roomId' : RoomId,
    'riskLevel' : RiskLevel,
  });
  const Tenant = IDL.Record({
    'id' : TenantId,
    'exitReason' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'checkInDate' : Timestamp,
    'idProof' : IDL.Text,
    'isActive' : IDL.Bool,
    'advancePaid' : IDL.Nat,
    'bedId' : BedId,
    'phone' : IDL.Text,
    'monthlyRent' : IDL.Nat,
    'roomId' : RoomId,
    'riskLevel' : RiskLevel,
  });
  const Bed = IDL.Record({
    'id' : BedId,
    'bedLabel' : IDL.Text,
    'tenantId' : IDL.Opt(TenantId),
    'isOccupied' : IDL.Bool,
    'roomId' : RoomId,
  });
  const DashboardStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalExpensesThisMonth' : IDL.Nat,
    'occupiedBeds' : IDL.Nat,
    'totalBeds' : IDL.Nat,
    'totalTenants' : IDL.Nat,
    'activeTenants' : IDL.Nat,
    'highRiskTenants' : IDL.Nat,
    'overduePayments' : IDL.Nat,
    'openComplaints' : IDL.Nat,
    'paidPayments' : IDL.Nat,
    'totalRooms' : IDL.Nat,
  });
  const MealRecordId = IDL.Nat;
  const MealRecord = IDL.Record({
    'id' : MealRecordId,
    'date' : Timestamp,
    'chargePerDay' : IDL.Nat,
    'tenantId' : TenantId,
    'isEating' : IDL.Bool,
  });
  const ToggleMealArgs = IDL.Record({
    'date' : Timestamp,
    'chargePerDay' : IDL.Nat,
    'tenantId' : TenantId,
    'isEating' : IDL.Bool,
  });
  const UpdateRoomArgs = IDL.Record({
    'id' : RoomId,
    'floor' : IDL.Nat,
    'isAC' : IDL.Bool,
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const UpdateTenantArgs = IDL.Record({
    'id' : TenantId,
    'exitReason' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'checkInDate' : Timestamp,
    'idProof' : IDL.Text,
    'isActive' : IDL.Bool,
    'advancePaid' : IDL.Nat,
    'bedId' : BedId,
    'phone' : IDL.Text,
    'monthlyRent' : IDL.Nat,
    'roomId' : RoomId,
    'riskLevel' : RiskLevel,
  });
  
  return IDL.Service({
    'addComplaint' : IDL.Func([AddComplaintArgs], [Complaint], []),
    'addExpense' : IDL.Func([AddExpenseArgs], [Expense], []),
    'addGuestLog' : IDL.Func([AddGuestLogArgs], [GuestLog], []),
    'addMicroCharge' : IDL.Func([AddMicroChargeArgs], [MicroCharge], []),
    'addParcel' : IDL.Func([AddParcelArgs], [Parcel], []),
    'addPayment' : IDL.Func([AddPaymentArgs], [Payment], []),
    'addRoom' : IDL.Func([AddRoomArgs], [Room], []),
    'addStaffTask' : IDL.Func([AddStaffTaskArgs], [StaffTask], []),
    'addTenant' : IDL.Func([AddTenantArgs], [Tenant], []),
    'assignBed' : IDL.Func([BedId, IDL.Opt(TenantId)], [IDL.Bool], []),
    'calculateMonthlyMessCharge' : IDL.Func(
        [TenantId, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'collectParcel' : IDL.Func([ParcelId], [IDL.Bool], []),
    'computeRiskLevel' : IDL.Func([TenantId, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteTenant' : IDL.Func([TenantId, IDL.Opt(IDL.Text)], [IDL.Bool], []),
    'freeBed' : IDL.Func([BedId], [IDL.Bool], []),
    'generateMonthlyPayments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Payment)],
        [],
      ),
    'getBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
    'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getComplaintsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getGuestLogs' : IDL.Func([], [IDL.Vec(GuestLog)], ['query']),
    'getGuestLogsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(GuestLog)],
        ['query'],
      ),
    'getInactiveTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'getMealRecords' : IDL.Func([], [IDL.Vec(MealRecord)], ['query']),
    'getMealRecordsByTenant' : IDL.Func(
        [TenantId],
        [IDL.Vec(MealRecord)],
        ['query'],
      ),
    'getMicroCharges' : IDL.Func([], [IDL.Vec(MicroCharge)], ['query']),
    'getOpenComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByTenant' : IDL.Func([TenantId], [IDL.Vec(Payment)], ['query']),
    'getPendingMicroCharges' : IDL.Func([], [IDL.Vec(MicroCharge)], ['query']),
    'getPendingTasks' : IDL.Func([], [IDL.Vec(StaffTask)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getStaffTasks' : IDL.Func([], [IDL.Vec(StaffTask)], ['query']),
    'getTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'getUncollectedParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getWhatsAppConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markChargeAddedToRent' : IDL.Func([MicroChargeId], [IDL.Bool], []),
    'sendWhatsAppReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'setWhatsAppConfig' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'toggleMeal' : IDL.Func([ToggleMealArgs], [MealRecord], []),
    'updateComplaintStatus' : IDL.Func(
        [ComplaintId, ComplaintStatus],
        [IDL.Bool],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [PaymentId, PaymentStatus, IDL.Opt(PaymentMethod), IDL.Opt(Timestamp)],
        [IDL.Bool],
        [],
      ),
    'updateRiskLevel' : IDL.Func([TenantId, RiskLevel], [IDL.Bool], []),
    'updateRoom' : IDL.Func([UpdateRoomArgs], [IDL.Bool], []),
    'updateTaskStatus' : IDL.Func([StaffTaskId, TaskStatus], [IDL.Bool], []),
    'updateTenant' : IDL.Func([UpdateTenantArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };