/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddComplaintArgs {
  'description' : string,
  'tenantId' : TenantId,
  'category' : ComplaintCategory,
}
export interface AddExpenseArgs {
  'month' : bigint,
  'year' : bigint,
  'splitType' : SplitType,
  'notes' : string,
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export interface AddGuestLogArgs {
  'checkIn' : Timestamp,
  'guestName' : string,
  'tenantId' : TenantId,
  'checkOut' : Timestamp,
  'extraCharge' : bigint,
}
export interface AddMicroChargeArgs {
  'description' : string,
  'tenantId' : TenantId,
  'amount' : bigint,
}
export interface AddParcelArgs { 'description' : string, 'tenantId' : TenantId }
export interface AddPaymentArgs {
  'status' : PaymentStatus,
  'method' : [] | [PaymentMethod],
  'month' : bigint,
  'year' : bigint,
  'tenantId' : TenantId,
  'paidDate' : [] | [Timestamp],
  'amount' : bigint,
}
export interface AddRoomArgs {
  'floor' : bigint,
  'isAC' : boolean,
  'number' : string,
  'capacity' : bigint,
}
export interface AddStaffTaskArgs {
  'title' : string,
  'assignedTo' : string,
  'dueDate' : Timestamp,
}
export interface AddTenantArgs {
  'name' : string,
  'checkInDate' : Timestamp,
  'idProof' : string,
  'advancePaid' : bigint,
  'bedId' : BedId,
  'phone' : string,
  'monthlyRent' : bigint,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
}
export interface Bed {
  'id' : BedId,
  'bedLabel' : string,
  'tenantId' : [] | [TenantId],
  'isOccupied' : boolean,
  'roomId' : RoomId,
}
export type BedId = bigint;
export interface Complaint {
  'id' : ComplaintId,
  'status' : ComplaintStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'tenantId' : TenantId,
  'category' : ComplaintCategory,
}
export type ComplaintCategory = { 'cleaning' : null } |
  { 'other' : null } |
  { 'electricity' : null } |
  { 'water' : null };
export type ComplaintId = bigint;
export type ComplaintStatus = { 'resolved' : null } |
  { 'open' : null };
export interface DashboardStats {
  'pendingPayments' : bigint,
  'totalExpensesThisMonth' : bigint,
  'occupiedBeds' : bigint,
  'totalBeds' : bigint,
  'totalTenants' : bigint,
  'activeTenants' : bigint,
  'highRiskTenants' : bigint,
  'overduePayments' : bigint,
  'openComplaints' : bigint,
  'paidPayments' : bigint,
  'totalRooms' : bigint,
}
export interface Expense {
  'id' : ExpenseId,
  'month' : bigint,
  'year' : bigint,
  'splitType' : SplitType,
  'notes' : string,
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export type ExpenseCategory = { 'other' : null } |
  { 'electricity' : null } |
  { 'generator' : null } |
  { 'maintenance' : null };
export type ExpenseId = bigint;
export interface GuestLog {
  'id' : GuestLogId,
  'checkIn' : Timestamp,
  'guestName' : string,
  'tenantId' : TenantId,
  'checkOut' : Timestamp,
  'extraCharge' : bigint,
}
export type GuestLogId = bigint;
export interface MealRecord {
  'id' : MealRecordId,
  'date' : Timestamp,
  'chargePerDay' : bigint,
  'tenantId' : TenantId,
  'isEating' : boolean,
}
export type MealRecordId = bigint;
export interface MicroCharge {
  'id' : MicroChargeId,
  'description' : string,
  'tenantId' : TenantId,
  'addedAt' : Timestamp,
  'amount' : bigint,
  'addedToRent' : boolean,
}
export type MicroChargeId = bigint;
export interface Parcel {
  'id' : ParcelId,
  'description' : string,
  'isCollected' : boolean,
  'tenantId' : TenantId,
  'receivedAt' : Timestamp,
}
export type ParcelId = bigint;
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'method' : [] | [PaymentMethod],
  'month' : bigint,
  'year' : bigint,
  'tenantId' : TenantId,
  'paidDate' : [] | [Timestamp],
  'amount' : bigint,
}
export type PaymentId = bigint;
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Room {
  'id' : RoomId,
  'floor' : bigint,
  'isAC' : boolean,
  'number' : string,
  'capacity' : bigint,
}
export type RoomId = bigint;
export type SplitType = { 'equal' : null } |
  { 'weighted' : null };
export interface StaffTask {
  'id' : StaffTaskId,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : string,
  'dueDate' : Timestamp,
}
export type StaffTaskId = bigint;
export type TaskStatus = { 'pending' : null } |
  { 'done' : null };
export interface Tenant {
  'id' : TenantId,
  'exitReason' : [] | [string],
  'name' : string,
  'checkInDate' : Timestamp,
  'idProof' : string,
  'isActive' : boolean,
  'advancePaid' : bigint,
  'bedId' : BedId,
  'phone' : string,
  'monthlyRent' : bigint,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
}
export type TenantId = bigint;
export type Timestamp = bigint;
export interface ToggleMealArgs {
  'date' : Timestamp,
  'chargePerDay' : bigint,
  'tenantId' : TenantId,
  'isEating' : boolean,
}
export interface UpdateRoomArgs {
  'id' : RoomId,
  'floor' : bigint,
  'isAC' : boolean,
  'number' : string,
  'capacity' : bigint,
}
export interface UpdateTenantArgs {
  'id' : TenantId,
  'exitReason' : [] | [string],
  'name' : string,
  'checkInDate' : Timestamp,
  'idProof' : string,
  'isActive' : boolean,
  'advancePaid' : bigint,
  'bedId' : BedId,
  'phone' : string,
  'monthlyRent' : bigint,
  'roomId' : RoomId,
  'riskLevel' : RiskLevel,
}
export interface _SERVICE {
  'addComplaint' : ActorMethod<[AddComplaintArgs], Complaint>,
  'addExpense' : ActorMethod<[AddExpenseArgs], Expense>,
  'addGuestLog' : ActorMethod<[AddGuestLogArgs], GuestLog>,
  'addMicroCharge' : ActorMethod<[AddMicroChargeArgs], MicroCharge>,
  'addParcel' : ActorMethod<[AddParcelArgs], Parcel>,
  'addPayment' : ActorMethod<[AddPaymentArgs], Payment>,
  'addRoom' : ActorMethod<[AddRoomArgs], Room>,
  'addStaffTask' : ActorMethod<[AddStaffTaskArgs], StaffTask>,
  'addTenant' : ActorMethod<[AddTenantArgs], Tenant>,
  'assignBed' : ActorMethod<[BedId, [] | [TenantId]], boolean>,
  'calculateMonthlyMessCharge' : ActorMethod<
    [TenantId, bigint, bigint],
    bigint
  >,
  'collectParcel' : ActorMethod<[ParcelId], boolean>,
  'computeRiskLevel' : ActorMethod<[TenantId, bigint, bigint], boolean>,
  'deleteTenant' : ActorMethod<[TenantId, [] | [string]], boolean>,
  'freeBed' : ActorMethod<[BedId], boolean>,
  'generateMonthlyPayments' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getBeds' : ActorMethod<[], Array<Bed>>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getComplaintsByTenant' : ActorMethod<[TenantId], Array<Complaint>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByMonth' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getGuestLogs' : ActorMethod<[], Array<GuestLog>>,
  'getGuestLogsByTenant' : ActorMethod<[TenantId], Array<GuestLog>>,
  'getInactiveTenants' : ActorMethod<[], Array<Tenant>>,
  'getMealRecords' : ActorMethod<[], Array<MealRecord>>,
  'getMealRecordsByTenant' : ActorMethod<[TenantId], Array<MealRecord>>,
  'getMicroCharges' : ActorMethod<[], Array<MicroCharge>>,
  'getOpenComplaints' : ActorMethod<[], Array<Complaint>>,
  'getParcels' : ActorMethod<[], Array<Parcel>>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getPaymentsByMonth' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getPaymentsByTenant' : ActorMethod<[TenantId], Array<Payment>>,
  'getPendingMicroCharges' : ActorMethod<[], Array<MicroCharge>>,
  'getPendingTasks' : ActorMethod<[], Array<StaffTask>>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'getStaffTasks' : ActorMethod<[], Array<StaffTask>>,
  'getTenants' : ActorMethod<[], Array<Tenant>>,
  'getUncollectedParcels' : ActorMethod<[], Array<Parcel>>,
  'getWhatsAppConfigured' : ActorMethod<[], boolean>,
  'markChargeAddedToRent' : ActorMethod<[MicroChargeId], boolean>,
  'sendWhatsAppReminder' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'setWhatsAppConfig' : ActorMethod<[string, string], boolean>,
  'toggleMeal' : ActorMethod<[ToggleMealArgs], MealRecord>,
  'updateComplaintStatus' : ActorMethod<
    [ComplaintId, ComplaintStatus],
    boolean
  >,
  'updatePaymentStatus' : ActorMethod<
    [PaymentId, PaymentStatus, [] | [PaymentMethod], [] | [Timestamp]],
    boolean
  >,
  'updateRiskLevel' : ActorMethod<[TenantId, RiskLevel], boolean>,
  'updateRoom' : ActorMethod<[UpdateRoomArgs], boolean>,
  'updateTaskStatus' : ActorMethod<[StaffTaskId, TaskStatus], boolean>,
  'updateTenant' : ActorMethod<[UpdateTenantArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];