/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Tenant {
    id: TenantId;
    exitReason?: string;
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
}
export interface UpdateRoomArgs {
    id: RoomId;
    floor: bigint;
    isAC: boolean;
    number: string;
    capacity: bigint;
}
export type GuestLogId = bigint;
export interface ToggleMealArgs {
    date: Timestamp;
    chargePerDay: bigint;
    tenantId: TenantId;
    isEating: boolean;
}
export type RoomId = bigint;
export interface Room {
    id: RoomId;
    floor: bigint;
    isAC: boolean;
    number: string;
    capacity: bigint;
}
export interface MicroCharge {
    id: MicroChargeId;
    description: string;
    tenantId: TenantId;
    addedAt: Timestamp;
    amount: bigint;
    addedToRent: boolean;
}
export interface GuestLog {
    id: GuestLogId;
    checkIn: Timestamp;
    guestName: string;
    tenantId: TenantId;
    checkOut: Timestamp;
    extraCharge: bigint;
}
export type MealRecordId = bigint;
export type StaffTaskId = bigint;
export interface StaffTask {
    id: StaffTaskId;
    status: TaskStatus;
    title: string;
    assignedTo: string;
    dueDate: Timestamp;
}
export interface AddTenantArgs {
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
}
export type MicroChargeId = bigint;
export interface AddParcelArgs {
    description: string;
    tenantId: TenantId;
}
export interface MealRecord {
    id: MealRecordId;
    date: Timestamp;
    chargePerDay: bigint;
    tenantId: TenantId;
    isEating: boolean;
}
export interface AddPaymentArgs {
    status: PaymentStatus;
    method?: PaymentMethod;
    month: bigint;
    year: bigint;
    tenantId: TenantId;
    paidDate?: Timestamp;
    amount: bigint;
}
export interface AddStaffTaskArgs {
    title: string;
    assignedTo: string;
    dueDate: Timestamp;
}
export interface Parcel {
    id: ParcelId;
    description: string;
    isCollected: boolean;
    tenantId: TenantId;
    receivedAt: Timestamp;
}
export type TenantId = bigint;
export type BedId = bigint;
export interface AddRoomArgs {
    floor: bigint;
    isAC: boolean;
    number: string;
    capacity: bigint;
}
export interface UpdateTenantArgs {
    id: TenantId;
    exitReason?: string;
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
}
export interface AddExpenseArgs {
    month: bigint;
    year: bigint;
    splitType: SplitType;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
}
export type ParcelId = bigint;
export interface Payment {
    id: PaymentId;
    status: PaymentStatus;
    method?: PaymentMethod;
    month: bigint;
    year: bigint;
    tenantId: TenantId;
    paidDate?: Timestamp;
    amount: bigint;
}
export interface Expense {
    id: ExpenseId;
    month: bigint;
    year: bigint;
    splitType: SplitType;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
}
export interface DashboardStats {
    pendingPayments: bigint;
    totalExpensesThisMonth: bigint;
    occupiedBeds: bigint;
    totalBeds: bigint;
    totalTenants: bigint;
    activeTenants: bigint;
    highRiskTenants: bigint;
    overduePayments: bigint;
    openComplaints: bigint;
    paidPayments: bigint;
    totalRooms: bigint;
}
export interface AddGuestLogArgs {
    checkIn: Timestamp;
    guestName: string;
    tenantId: TenantId;
    checkOut: Timestamp;
    extraCharge: bigint;
}
export interface AddMicroChargeArgs {
    description: string;
    tenantId: TenantId;
    amount: bigint;
}
export type PaymentId = bigint;
export interface Complaint {
    id: ComplaintId;
    status: ComplaintStatus;
    createdAt: Timestamp;
    description: string;
    tenantId: TenantId;
    category: ComplaintCategory;
}
export type ExpenseId = bigint;
export type ComplaintId = bigint;
export interface Bed {
    id: BedId;
    bedLabel: string;
    tenantId?: TenantId;
    isOccupied: boolean;
    roomId: RoomId;
}
export interface AddComplaintArgs {
    description: string;
    tenantId: TenantId;
    category: ComplaintCategory;
}
export enum ComplaintCategory {
    cleaning = "cleaning",
    other = "other",
    electricity = "electricity",
    water = "water"
}
export enum ComplaintStatus {
    resolved = "resolved",
    open = "open"
}
export enum ExpenseCategory {
    other = "other",
    electricity = "electricity",
    generator = "generator",
    maintenance = "maintenance"
}
export enum PaymentMethod {
    upi = "upi",
    cash = "cash"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum SplitType {
    equal = "equal",
    weighted = "weighted"
}
export enum TaskStatus {
    pending = "pending",
    done = "done"
}
export interface backendInterface {
    addComplaint(args: AddComplaintArgs): Promise<Complaint>;
    addExpense(args: AddExpenseArgs): Promise<Expense>;
    addGuestLog(args: AddGuestLogArgs): Promise<GuestLog>;
    addMicroCharge(args: AddMicroChargeArgs): Promise<MicroCharge>;
    addParcel(args: AddParcelArgs): Promise<Parcel>;
    addPayment(args: AddPaymentArgs): Promise<Payment>;
    addRoom(args: AddRoomArgs): Promise<Room>;
    addStaffTask(args: AddStaffTaskArgs): Promise<StaffTask>;
    addTenant(args: AddTenantArgs): Promise<Tenant>;
    assignBed(bedId: BedId, tenantId: TenantId | null): Promise<boolean>;
    calculateMonthlyMessCharge(tenantId: TenantId, month: bigint, year: bigint): Promise<bigint>;
    collectParcel(id: ParcelId): Promise<boolean>;
    computeRiskLevel(id: TenantId, latePaymentCount: bigint, complaintCount: bigint): Promise<boolean>;
    deleteTenant(id: TenantId, exitReason: string | null): Promise<boolean>;
    freeBed(bedId: BedId): Promise<boolean>;
    generateMonthlyPayments(month: bigint, year: bigint): Promise<Array<Payment>>;
    getBeds(): Promise<Array<Bed>>;
    getComplaints(): Promise<Array<Complaint>>;
    getComplaintsByTenant(tenantId: TenantId): Promise<Array<Complaint>>;
    getDashboardStats(): Promise<DashboardStats>;
    getExpenses(): Promise<Array<Expense>>;
    getExpensesByMonth(month: bigint, year: bigint): Promise<Array<Expense>>;
    getGuestLogs(): Promise<Array<GuestLog>>;
    getGuestLogsByTenant(tenantId: TenantId): Promise<Array<GuestLog>>;
    getInactiveTenants(): Promise<Array<Tenant>>;
    getMealRecords(): Promise<Array<MealRecord>>;
    getMealRecordsByTenant(tenantId: TenantId): Promise<Array<MealRecord>>;
    getMicroCharges(): Promise<Array<MicroCharge>>;
    getOpenComplaints(): Promise<Array<Complaint>>;
    getParcels(): Promise<Array<Parcel>>;
    getPayments(): Promise<Array<Payment>>;
    getPaymentsByMonth(month: bigint, year: bigint): Promise<Array<Payment>>;
    getPaymentsByTenant(tenantId: TenantId): Promise<Array<Payment>>;
    getPendingMicroCharges(): Promise<Array<MicroCharge>>;
    getPendingTasks(): Promise<Array<StaffTask>>;
    getRooms(): Promise<Array<Room>>;
    getStaffTasks(): Promise<Array<StaffTask>>;
    getTenants(): Promise<Array<Tenant>>;
    getUncollectedParcels(): Promise<Array<Parcel>>;
    getWhatsAppConfigured(): Promise<boolean>;
    markChargeAddedToRent(id: MicroChargeId): Promise<boolean>;
    sendWhatsAppReminder(tenantPhone: string, tenantName: string, amount: bigint, month: string): Promise<{
        ok: boolean;
        message: string;
    }>;
    setWhatsAppConfig(phoneNumberId: string, accessToken: string): Promise<boolean>;
    toggleMeal(args: ToggleMealArgs): Promise<MealRecord>;
    updateComplaintStatus(id: ComplaintId, status: ComplaintStatus): Promise<boolean>;
    updatePaymentStatus(id: PaymentId, status: PaymentStatus, method: PaymentMethod | null, paidDate: Timestamp | null): Promise<boolean>;
    updateRiskLevel(id: TenantId, riskLevel: RiskLevel): Promise<boolean>;
    updateRoom(args: UpdateRoomArgs): Promise<boolean>;
    updateTaskStatus(id: StaffTaskId, status: TaskStatus): Promise<boolean>;
    updateTenant(args: UpdateTenantArgs): Promise<boolean>;
}
import type { AddComplaintArgs as _AddComplaintArgs, AddExpenseArgs as _AddExpenseArgs, AddPaymentArgs as _AddPaymentArgs, AddTenantArgs as _AddTenantArgs, Bed as _Bed, BedId as _BedId, Complaint as _Complaint, ComplaintCategory as _ComplaintCategory, ComplaintId as _ComplaintId, ComplaintStatus as _ComplaintStatus, Expense as _Expense, ExpenseCategory as _ExpenseCategory, ExpenseId as _ExpenseId, Payment as _Payment, PaymentId as _PaymentId, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, RiskLevel as _RiskLevel, RoomId as _RoomId, SplitType as _SplitType, StaffTask as _StaffTask, StaffTaskId as _StaffTaskId, TaskStatus as _TaskStatus, Tenant as _Tenant, TenantId as _TenantId, Timestamp as _Timestamp, UpdateTenantArgs as _UpdateTenantArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComplaint(arg0: AddComplaintArgs): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComplaint(to_candid_AddComplaintArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Complaint_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComplaint(to_candid_AddComplaintArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Complaint_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addExpense(arg0: AddExpenseArgs): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_AddExpenseArgs_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expense_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_AddExpenseArgs_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expense_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGuestLog(arg0: AddGuestLogArgs): Promise<GuestLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuestLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuestLog(arg0);
            return result;
        }
    }
    async addMicroCharge(arg0: AddMicroChargeArgs): Promise<MicroCharge> {
        if (this.processError) {
            try {
                const result = await this.actor.addMicroCharge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMicroCharge(arg0);
            return result;
        }
    }
    async addParcel(arg0: AddParcelArgs): Promise<Parcel> {
        if (this.processError) {
            try {
                const result = await this.actor.addParcel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParcel(arg0);
            return result;
        }
    }
    async addPayment(arg0: AddPaymentArgs): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_AddPaymentArgs_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_AddPaymentArgs_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRoom(arg0: AddRoomArgs): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(arg0);
            return result;
        }
    }
    async addStaffTask(arg0: AddStaffTaskArgs): Promise<StaffTask> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffTask(arg0);
                return from_candid_StaffTask_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffTask(arg0);
            return from_candid_StaffTask_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTenant(arg0: AddTenantArgs): Promise<Tenant> {
        if (this.processError) {
            try {
                const result = await this.actor.addTenant(to_candid_AddTenantArgs_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Tenant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTenant(to_candid_AddTenantArgs_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Tenant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignBed(arg0: BedId, arg1: TenantId | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBed(arg0, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBed(arg0, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateMonthlyMessCharge(arg0: TenantId, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateMonthlyMessCharge(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateMonthlyMessCharge(arg0, arg1, arg2);
            return result;
        }
    }
    async collectParcel(arg0: ParcelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.collectParcel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectParcel(arg0);
            return result;
        }
    }
    async computeRiskLevel(arg0: TenantId, arg1: bigint, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.computeRiskLevel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeRiskLevel(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteTenant(arg0: TenantId, arg1: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTenant(arg0, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTenant(arg0, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async freeBed(arg0: BedId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.freeBed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.freeBed(arg0);
            return result;
        }
    }
    async generateMonthlyPayments(arg0: bigint, arg1: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMonthlyPayments(arg0, arg1);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMonthlyPayments(arg0, arg1);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBeds(): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBeds();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBeds();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaints();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaints();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByTenant(arg0: TenantId): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByTenant(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByTenant(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByMonth(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMonth(arg0, arg1);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMonth(arg0, arg1);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuestLogs(): Promise<Array<GuestLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestLogs();
            return result;
        }
    }
    async getGuestLogsByTenant(arg0: TenantId): Promise<Array<GuestLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestLogsByTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestLogsByTenant(arg0);
            return result;
        }
    }
    async getInactiveTenants(): Promise<Array<Tenant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveTenants();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveTenants();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealRecords(): Promise<Array<MealRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealRecords();
            return result;
        }
    }
    async getMealRecordsByTenant(arg0: TenantId): Promise<Array<MealRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealRecordsByTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealRecordsByTenant(arg0);
            return result;
        }
    }
    async getMicroCharges(): Promise<Array<MicroCharge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMicroCharges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMicroCharges();
            return result;
        }
    }
    async getOpenComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenComplaints();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenComplaints();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParcels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParcels();
            return result;
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByMonth(arg0: bigint, arg1: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByMonth(arg0, arg1);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByMonth(arg0, arg1);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByTenant(arg0: TenantId): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByTenant(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByTenant(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingMicroCharges(): Promise<Array<MicroCharge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingMicroCharges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingMicroCharges();
            return result;
        }
    }
    async getPendingTasks(): Promise<Array<StaffTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTasks();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTasks();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRooms();
            return result;
        }
    }
    async getStaffTasks(): Promise<Array<StaffTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffTasks();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffTasks();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTenants(): Promise<Array<Tenant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTenants();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTenants();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUncollectedParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUncollectedParcels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUncollectedParcels();
            return result;
        }
    }
    async getWhatsAppConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhatsAppConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhatsAppConfigured();
            return result;
        }
    }
    async markChargeAddedToRent(arg0: MicroChargeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markChargeAddedToRent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markChargeAddedToRent(arg0);
            return result;
        }
    }
    async sendWhatsAppReminder(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<{
        ok: boolean;
        message: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendWhatsAppReminder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendWhatsAppReminder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setWhatsAppConfig(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setWhatsAppConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWhatsAppConfig(arg0, arg1);
            return result;
        }
    }
    async toggleMeal(arg0: ToggleMealArgs): Promise<MealRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMeal(arg0);
            return result;
        }
    }
    async updateComplaintStatus(arg0: ComplaintId, arg1: ComplaintStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_ComplaintStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: PaymentId, arg1: PaymentStatus, arg2: PaymentMethod | null, arg3: Timestamp | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateRiskLevel(arg0: TenantId, arg1: RiskLevel): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiskLevel(arg0, to_candid_RiskLevel_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiskLevel(arg0, to_candid_RiskLevel_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRoom(arg0: UpdateRoomArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoom(arg0);
            return result;
        }
    }
    async updateTaskStatus(arg0: StaffTaskId, arg1: TaskStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTenant(arg0: UpdateTenantArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTenant(to_candid_UpdateTenantArgs_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTenant(to_candid_UpdateTenantArgs_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Bed_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bed): Bed {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ComplaintCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintCategory): ComplaintCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ComplaintStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplaintStatus): ComplaintStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Complaint_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_SplitType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SplitType): SplitType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StaffTask_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffTask): StaffTask {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Tenant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tenant): Tenant {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TenantId]): TenantId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    month: bigint;
    year: bigint;
    splitType: _SplitType;
    notes: string;
    category: _ExpenseCategory;
    amount: bigint;
}): {
    id: ExpenseId;
    month: bigint;
    year: bigint;
    splitType: SplitType;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        month: value.month,
        year: value.year,
        splitType: from_candid_SplitType_n19(_uploadFile, _downloadFile, value.splitType),
        notes: value.notes,
        category: from_candid_ExpenseCategory_n21(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentStatus;
    method: [] | [_PaymentMethod];
    month: bigint;
    year: bigint;
    tenantId: _TenantId;
    paidDate: [] | [_Timestamp];
    amount: bigint;
}): {
    id: PaymentId;
    status: PaymentStatus;
    method?: PaymentMethod;
    month: bigint;
    year: bigint;
    tenantId: TenantId;
    paidDate?: Timestamp;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n31(_uploadFile, _downloadFile, value.status),
        method: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.method)),
        month: value.month,
        year: value.year,
        tenantId: value.tenantId,
        paidDate: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.paidDate)),
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StaffTaskId;
    status: _TaskStatus;
    title: string;
    assignedTo: string;
    dueDate: _Timestamp;
}): {
    id: StaffTaskId;
    status: TaskStatus;
    title: string;
    assignedTo: string;
    dueDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n39(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        dueDate: value.dueDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TenantId;
    exitReason: [] | [string];
    name: string;
    checkInDate: _Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: _BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: _RoomId;
    riskLevel: _RiskLevel;
}): {
    id: TenantId;
    exitReason?: string;
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
} {
    return {
        id: value.id,
        exitReason: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.exitReason)),
        name: value.name,
        checkInDate: value.checkInDate,
        idProof: value.idProof,
        isActive: value.isActive,
        advancePaid: value.advancePaid,
        bedId: value.bedId,
        phone: value.phone,
        monthlyRent: value.monthlyRent,
        roomId: value.roomId,
        riskLevel: from_candid_RiskLevel_n48(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BedId;
    bedLabel: string;
    tenantId: [] | [_TenantId];
    isOccupied: boolean;
    roomId: _RoomId;
}): {
    id: BedId;
    bedLabel: string;
    tenantId?: TenantId;
    isOccupied: boolean;
    roomId: RoomId;
} {
    return {
        id: value.id,
        bedLabel: value.bedLabel,
        tenantId: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.tenantId)),
        isOccupied: value.isOccupied,
        roomId: value.roomId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ComplaintId;
    status: _ComplaintStatus;
    createdAt: _Timestamp;
    description: string;
    tenantId: _TenantId;
    category: _ComplaintCategory;
}): {
    id: ComplaintId;
    status: ComplaintStatus;
    createdAt: Timestamp;
    description: string;
    tenantId: TenantId;
    category: ComplaintCategory;
} {
    return {
        id: value.id,
        status: from_candid_ComplaintStatus_n7(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        description: value.description,
        tenantId: value.tenantId,
        category: from_candid_ComplaintCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cleaning: null;
} | {
    other: null;
} | {
    electricity: null;
} | {
    water: null;
}): ComplaintCategory {
    return "cleaning" in value ? ComplaintCategory.cleaning : "other" in value ? ComplaintCategory.other : "electricity" in value ? ComplaintCategory.electricity : "water" in value ? ComplaintCategory.water : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equal: null;
} | {
    weighted: null;
}): SplitType {
    return "equal" in value ? SplitType.equal : "weighted" in value ? SplitType.weighted : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    electricity: null;
} | {
    generator: null;
} | {
    maintenance: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "electricity" in value ? ExpenseCategory.electricity : "generator" in value ? ExpenseCategory.generator : "maintenance" in value ? ExpenseCategory.maintenance : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "overdue" in value ? PaymentStatus.overdue : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "done" in value ? TaskStatus.done : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
}): ComplaintStatus {
    return "resolved" in value ? ComplaintStatus.resolved : "open" in value ? ComplaintStatus.open : value;
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bed>): Array<Bed> {
    return value.map((x)=>from_candid_Bed_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tenant>): Array<Tenant> {
    return value.map((x)=>from_candid_Tenant_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffTask>): Array<StaffTask> {
    return value.map((x)=>from_candid_StaffTask_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AddComplaintArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddComplaintArgs): _AddComplaintArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AddExpenseArgs_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddExpenseArgs): _AddExpenseArgs {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_AddPaymentArgs_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddPaymentArgs): _AddPaymentArgs {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_AddTenantArgs_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddTenantArgs): _AddTenantArgs {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ComplaintCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintCategory): _ComplaintCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ComplaintStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): _ComplaintStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_SplitType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SplitType): _SplitType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTenantArgs_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTenantArgs): _UpdateTenantArgs {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantId | null): [] | [_TenantId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod | null): [] | [_PaymentMethod] {
    return value === null ? candid_none() : candid_some(to_candid_PaymentMethod_n27(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: bigint;
    year: bigint;
    splitType: SplitType;
    notes: string;
    category: ExpenseCategory;
    amount: bigint;
}): {
    month: bigint;
    year: bigint;
    splitType: _SplitType;
    notes: string;
    category: _ExpenseCategory;
    amount: bigint;
} {
    return {
        month: value.month,
        year: value.year,
        splitType: to_candid_SplitType_n13(_uploadFile, _downloadFile, value.splitType),
        notes: value.notes,
        category: to_candid_ExpenseCategory_n15(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    tenantId: TenantId;
    category: ComplaintCategory;
}): {
    description: string;
    tenantId: _TenantId;
    category: _ComplaintCategory;
} {
    return {
        description: value.description,
        tenantId: value.tenantId,
        category: to_candid_ComplaintCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PaymentStatus;
    method?: PaymentMethod;
    month: bigint;
    year: bigint;
    tenantId: TenantId;
    paidDate?: Timestamp;
    amount: bigint;
}): {
    status: _PaymentStatus;
    method: [] | [_PaymentMethod];
    month: bigint;
    year: bigint;
    tenantId: _TenantId;
    paidDate: [] | [_Timestamp];
    amount: bigint;
} {
    return {
        status: to_candid_PaymentStatus_n25(_uploadFile, _downloadFile, value.status),
        method: value.method ? candid_some(to_candid_PaymentMethod_n27(_uploadFile, _downloadFile, value.method)) : candid_none(),
        month: value.month,
        year: value.year,
        tenantId: value.tenantId,
        paidDate: value.paidDate ? candid_some(value.paidDate) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
}): {
    name: string;
    checkInDate: _Timestamp;
    idProof: string;
    advancePaid: bigint;
    bedId: _BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: _RoomId;
    riskLevel: _RiskLevel;
} {
    return {
        name: value.name,
        checkInDate: value.checkInDate,
        idProof: value.idProof,
        advancePaid: value.advancePaid,
        bedId: value.bedId,
        phone: value.phone,
        monthlyRent: value.monthlyRent,
        roomId: value.roomId,
        riskLevel: to_candid_RiskLevel_n43(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TenantId;
    exitReason?: string;
    name: string;
    checkInDate: Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: RoomId;
    riskLevel: RiskLevel;
}): {
    id: _TenantId;
    exitReason: [] | [string];
    name: string;
    checkInDate: _Timestamp;
    idProof: string;
    isActive: boolean;
    advancePaid: bigint;
    bedId: _BedId;
    phone: string;
    monthlyRent: bigint;
    roomId: _RoomId;
    riskLevel: _RiskLevel;
} {
    return {
        id: value.id,
        exitReason: value.exitReason ? candid_some(value.exitReason) : candid_none(),
        name: value.name,
        checkInDate: value.checkInDate,
        idProof: value.idProof,
        isActive: value.isActive,
        advancePaid: value.advancePaid,
        bedId: value.bedId,
        phone: value.phone,
        monthlyRent: value.monthlyRent,
        roomId: value.roomId,
        riskLevel: to_candid_RiskLevel_n43(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SplitType): {
    equal: null;
} | {
    weighted: null;
} {
    return value == SplitType.equal ? {
        equal: null
    } : value == SplitType.weighted ? {
        weighted: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    electricity: null;
} | {
    generator: null;
} | {
    maintenance: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.electricity ? {
        electricity: null
    } : value == ExpenseCategory.generator ? {
        generator: null
    } : value == ExpenseCategory.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintCategory): {
    cleaning: null;
} | {
    other: null;
} | {
    electricity: null;
} | {
    water: null;
} {
    return value == ComplaintCategory.cleaning ? {
        cleaning: null
    } : value == ComplaintCategory.other ? {
        other: null
    } : value == ComplaintCategory.electricity ? {
        electricity: null
    } : value == ComplaintCategory.water ? {
        water: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintStatus): {
    resolved: null;
} | {
    open: null;
} {
    return value == ComplaintStatus.resolved ? {
        resolved: null
    } : value == ComplaintStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    done: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.done ? {
        done: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
